# Generated by Django 2.1.5 on 2022-02-05 17:41

import ckeditor.fields
from django.db import migrations, models
import fontawesome_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=200)),
                ('page_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='photo_about/%Y/%m/%d')),
                ('body', ckeditor.fields.RichTextField()),
                ('work_title', models.CharField(max_length=200)),
                ('summary_work', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('summary', models.CharField(max_length=200)),
                ('icon1', fontawesome_5.fields.IconField(blank=True, max_length=60)),
                ('icon2', fontawesome_5.fields.IconField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=200)),
                ('menu_title1', models.CharField(max_length=200)),
                ('menu_title2', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('page_title', models.CharField(max_length=200)),
                ('card_title', models.CharField(max_length=200)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, upload_to='logo/%Y/%m/%d')),
                ('publish', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name': 'صفحات',
                'verbose_name_plural': 'صفحات',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
                ('png', models.ImageField(blank=True, upload_to='png/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Subfooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'خدمات ما',
                'verbose_name_plural': 'خدمات ما',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='social',
            field=models.ManyToManyField(related_name='page', to='blog.Social'),
        ),
    ]
